apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-udacity-app
  namespace: hello-udacity-app
  labels:
    app: hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-udacity-app
  template:
    metadata:
      labels:
        app: hello-udacity--app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: hello-udacity-app
          image: vineetrai089/hello-udacity-image:latest
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/os: linux
