apiVersion: v1
kind: Service
metadata:
  name: hello-udacity-app
  namespace:
  labels:
    app: hello-udacity-app
spec:
  selector:
    app: hello-udacity-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
